# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifier-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # ↓↓↓ この行を変更したで！ ↓↓↓
    command: sh -c "bun install && bun run dev"
    tty: true
    stdin_open: true
